### ISSUE TITLE
Projects integration: Progress bar styling

### ISSUE THREAD

**Issue by maxelkins** [RaspberryPiFoundation/editor-ui#873]
## Progress bar and styling incorrect

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/59e7457b-002e-4a56-8b51-1baf5bc04732)

![Image](https://github.com/RaspberryPiFoundation/editor-ui/assets/43481548/b12135db-795a-4dfc-b6e0-379e09f27dad)

## To do

- Remove the max-wdith from the progress bar, it should fill the space
- If we want to use the progress element then we need to style it using the browser prefixes. I've put an example below. This should reset, remove borders, set border radius, do all the colours.
- Disabled button style needs tweaking - [design](https://www.figma.com/file/k8HLf9t06G8QtlMzQlgHGk/RPF-Design-System---Component-Library?type=design&node-id=407-725&mode=design&t=1AWrwUVQihHQNyOF-4)

``` css
progress{
  --progress-background: red;
  --progress-inner: navy;
  --progress-height: 0.5rem; /* 8px */
  --progress-radius: var(--progress-height);

  /* Reset all */
  -webkit-appearance: none;
   appearance: none;

  block-size: var(--progress-height);
  
  /* Needed for Firefox */
  /* This is the background of the bar */
  border:none;
  background-color: var(--progress-background);
  border-radius: var(--progress-radius);

}

/* Needed for Firefox */
/* This is the inner bar */
progress::-moz-progress-bar {
  background-color: var(--progress-inner);
  border-radius: var(--progress-radius);
}


/* Needed for Chrome/Safari/Edge */
/* This is the background of the bar */
progress::-webkit-progress-bar {
  border-radius: var(--progress-radius);
  background-color: var(--progress-background);

}

/* This is the inner bar */
progress::-webkit-progress-value {
  background-color: var(--progress-inner);
  border-radius: var(--progress-radius);

}



```
